### ISSUE TITLE
[Root-Task] UI작업

### ISSUE THREAD

**Issue by juo1221** [juo1221/wanted-codestates-project-3#1]
### TODO
 - [x] (available, selected)options style 구현
 - [x] 버튼 style 구현
 - [x] 소메뉴 style 구현
