### ISSUE TITLE
셀렉터

### ISSUE THREAD

**Issue by juo1221** [juo1221/wanted-codestates-project-3#3]
### Todo 
- [x] 검색 기능 구현
- [x] 아이템 이동 기능 구현
- [x] 아이템 렌더링 기능 구현
- [x] 클릭된 아이템 개수 구현
- [x] selected options 생성 및 기능 적용
