### ISSUE TITLE
소메뉴

### ISSUE THREAD

**Issue by juo1221** [juo1221/wanted-codestates-project-3#4]
### Todo
- [x] 제목 수정 기능 구현
- [x] 하나씩 옮기기 기능 구현
- [x] 아이템 크기 조절 기능 구현
- [x] 영역 크기 조절 기능 구현
- [x] 검색 비활성화 기능 구현
