### ISSUE TITLE
리팩토링(MVC)

### ISSUE THREAD

**Issue by juo1221** [juo1221/wanted-codestates-project-3#7]
### Todo 
- [x] Model 구현
- [x] View 구현
- [x] Controller 구현
- [x] App 구현
- [x] util 함수 추가
- [x] data load하기 
- [x] item 클릭 시 상태 변경
- [x] 검색 기능 구현
- [x] reset 기능 구현
- [x] 오른쪽 이동기능 구현
- [x] 검색오류 해결
- [x] 왼쪽 이동기능 구현
- [x] 왼쪽으로 모두 이동기능 구현
- [x] searchOpt 검색 기능 구현
- [x] reset 로직 변경
- [x] 타이틀 변경기능 구현
- [x] 타이틀 readonly 기능 구현
- [x] CheckBoxModelS로 searchBar 제한 기능 구현
- [x] 라디오 토글 시 item 클래스 네임 변경 기능 구현
- [x] container 크기 변경 기능 구현
- [x] 높이변경 에러 수정
- [x] 하나씩만 옮기기 기능 구현
- [x] 선택된 아이템 개수 표시 기능 구현
- [x] 라디오 버튼 오류 수정
- [x] setting 렌더링 오류 수정 
- [x] 아이템 move시 상태 초기화 오류 수정
- [x] shift 기능 추가
